// Mock data for development - replace with real database calls
import type {
  Package,
  ServiceProvider,
  PackagePurchase,
  Appointment,
  Category,
  AdminStats,
  AdminUser,
  CommissionSettings,
  Transaction,
  Message,
  Conversation,
  AvailableSlot,
  User,
} from "./types"

const hashPassword = (password: string): string => {
  // Mock hashing - in production use bcrypt
  return Buffer.from(password).toString("base64")
}

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Spor ve Fitness",
    slug: "spor-fitness",
    description: "Pilates, yoga, kişisel antrenman ve fitness hizmetleri",
    icon: "dumbbell",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Sağlık ve Wellness",
    slug: "saglik-wellness",
    description: "Masaj, terapi ve sağlık hizmetleri",
    icon: "heart",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Eğitim",
    slug: "egitim",
    description: "Özel ders, kurs ve eğitim hizmetleri",
    icon: "book",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
]

export const mockServiceProvider: ServiceProvider = {
  id: "1",
  userId: "2",
  businessName: "Wellness Studio",
  description: "Profesyonel pilates ve yoga eğitimi",
  specialization: "Pilates, Yoga, Kişisel Antrenman",
  locationCity: "İstanbul",
  locationDistrict: "Kadıköy",
  locationAddress: "Moda Caddesi No: 123",
  rating: 4.8,
  totalReviews: 156,
  isVerified: true,
  isFeatured: false,
  commissionRate: 10.0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

export const mockPackages: Package[] = [
  {
    id: "1",
    serviceProviderId: "1",
    categoryId: "1",
    title: "10 Seans Pilates Paketi",
    description: "Profesyonel pilates eğitimi ile vücut şekillendirme",
    price: 1200,
    sessionCount: 10,
    durationMinutes: 60,
    validityDays: 90,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    serviceProviderId: "1",
    categoryId: "1",
    title: "5 Seans Yoga Paketi",
    description: "Hatha yoga ile zihin ve beden uyumu",
    price: 750,
    sessionCount: 5,
    durationMinutes: 75,
    validityDays: 60,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockPurchases: PackagePurchase[] = [
  {
    id: "1",
    customerId: "3",
    packageId: "1",
    serviceProviderId: "1",
    originalPrice: 1200,
    finalPrice: 1200,
    commissionAmount: 120,
    sessionsTotal: 10,
    sessionsUsed: 3,
    sessionsRemaining: 7,
    purchaseDate: new Date().toISOString(),
    expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    paymentStatus: "completed",
    paymentMethod: "credit_card",
    transactionId: "tx_123456",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    packagePurchaseId: "1",
    customerId: "3",
    serviceProviderId: "1",
    appointmentDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "10:00",
    endTime: "11:00",
    status: "confirmed",
    notes: "İlk seans",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockCustomerPackages: (Package & {
  serviceProvider?: ServiceProvider
  category?: Category
  salesCount?: number
})[] = [
  {
    id: "1",
    serviceProviderId: "1",
    categoryId: "1",
    title: "10 Seans Pilates Paketi",
    description:
      "Profesyonel pilates eğitimi ile vücut şekillendirme. Uzman eğitmenler eşliğinde kişiselleştirilmiş antrenman programı.",
    price: 1200,
    sessionCount: 10,
    durationMinutes: 60,
    validityDays: 90,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 156,
    serviceProvider: mockServiceProvider,
    category: mockCategories[0],
  },
  {
    id: "2",
    serviceProviderId: "1",
    categoryId: "1",
    title: "5 Seans Yoga Paketi",
    description: "Hatha yoga ile zihin ve beden uyumu. Stres azaltma ve esneklik artırma odaklı seanslar.",
    price: 750,
    sessionCount: 5,
    durationMinutes: 75,
    validityDays: 60,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 89,
    serviceProvider: mockServiceProvider,
    category: mockCategories[0],
  },
  {
    id: "3",
    serviceProviderId: "2",
    categoryId: "2",
    title: "8 Seans Masaj Terapisi",
    description: "Rahatlatıcı İsveç masajı ile kas gerginliklerini giderin. Profesyonel terapi uzmanı eşliğinde.",
    price: 2400,
    sessionCount: 8,
    durationMinutes: 90,
    validityDays: 120,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 234,
    serviceProvider: {
      ...mockServiceProvider,
      id: "2",
      businessName: "Wellness Spa Center",
      specialization: "Masaj Terapisi, Aromaterapi",
      locationCity: "İstanbul",
      locationDistrict: "Beşiktaş",
      rating: 4.9,
      totalReviews: 89,
    },
    category: mockCategories[1],
  },
  {
    id: "4",
    serviceProviderId: "3",
    categoryId: "3",
    title: "12 Ders İngilizce Paketi",
    description:
      "Birebir İngilizce dersleri ile konuşma becerinizi geliştirin. Online veya yüz yüze seçenekleri mevcut.",
    price: 800,
    sessionCount: 12,
    durationMinutes: 50,
    validityDays: 90,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 67,
    serviceProvider: {
      ...mockServiceProvider,
      id: "3",
      businessName: "English Academy",
      specialization: "İngilizce Eğitimi, IELTS Hazırlık",
      locationCity: "Online",
      locationDistrict: "Online",
      rating: 4.7,
      totalReviews: 234,
    },
    category: mockCategories[2],
  },
  {
    id: "5",
    serviceProviderId: "4",
    categoryId: "1",
    title: "6 Seans Kişisel Antrenman",
    description: "Birebir kişisel antrenman ile hedeflerinize ulaşın. Beslenme danışmanlığı dahil.",
    price: 1800,
    sessionCount: 6,
    durationMinutes: 60,
    validityDays: 60,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 198,
    serviceProvider: {
      ...mockServiceProvider,
      id: "4",
      businessName: "FitLife Gym",
      specialization: "Kişisel Antrenman, Beslenme",
      locationCity: "Ankara",
      locationDistrict: "Çankaya",
      rating: 4.9,
      totalReviews: 145,
    },
    category: mockCategories[0],
  },
  {
    id: "6",
    serviceProviderId: "5",
    categoryId: "2",
    title: "4 Seans Aromaterapi Masajı",
    description: "Doğal yağlarla yapılan aromaterapi masajı ile ruhunuzu dinlendirin.",
    price: 1600,
    sessionCount: 4,
    durationMinutes: 90,
    validityDays: 45,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    salesCount: 123,
    serviceProvider: {
      ...mockServiceProvider,
      id: "5",
      businessName: "Zen Spa",
      specialization: "Aromaterapi, Refleksoloji",
      locationCity: "İzmir",
      locationDistrict: "Alsancak",
      rating: 4.8,
      totalReviews: 78,
    },
    category: mockCategories[1],
  },
]

export const mockFeaturedPackages = mockCustomerPackages.filter((pkg) => pkg.isFeatured)

export const mockCustomerPurchases: (PackagePurchase & { package?: Package; serviceProvider?: ServiceProvider })[] = [
  {
    id: "1",
    customerId: "3",
    packageId: "1",
    serviceProviderId: "1",
    originalPrice: 1200,
    finalPrice: 1200,
    commissionAmount: 120,
    sessionsTotal: 10,
    sessionsUsed: 3,
    sessionsRemaining: 7,
    purchaseDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 83 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    paymentStatus: "completed",
    paymentMethod: "credit_card",
    transactionId: "tx_123456",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    package: mockCustomerPackages[0],
    serviceProvider: mockServiceProvider,
  },
]

export const mockAdminStats: AdminStats = {
  totalUsers: 1247,
  totalServiceProviders: 89,
  totalCustomers: 1158,
  totalPackages: 234,
  activePackages: 198,
  totalSales: 125600,
  totalCommission: 12560,
  monthlyGrowth: 15.2,
  topCategories: [
    { name: "Spor ve Fitness", count: 89, percentage: 38 },
    { name: "Sağlık ve Wellness", count: 67, percentage: 29 },
    { name: "Eğitim", count: 45, percentage: 19 },
    { name: "Güzellik ve Bakım", count: 33, percentage: 14 },
  ],
}

export const mockAdminUsers: AdminUser[] = [
  {
    id: "1",
    email: "admin@paresapp.online",
    userType: "admin",
    firstName: "Admin",
    lastName: "User",
    isActive: true,
    emailVerified: true,
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    email: "provider1@example.com",
    userType: "service_provider",
    firstName: "Ayşe",
    lastName: "Yılmaz",
    isActive: true,
    emailVerified: true,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    serviceProvider: {
      businessName: "Wellness Studio",
      isVerified: true,
      rating: 4.8,
      totalSales: 15600,
      commission: 1560,
    },
  },
  {
    id: "3",
    email: "customer1@example.com",
    userType: "customer",
    firstName: "Mehmet",
    lastName: "Demir",
    isActive: true,
    emailVerified: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    totalSpent: 2400,
    packageCount: 2,
  },
  {
    id: "4",
    email: "provider2@example.com",
    userType: "service_provider",
    firstName: "Can",
    lastName: "Özkan",
    isActive: false,
    emailVerified: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    serviceProvider: {
      businessName: "Fitness Center",
      isVerified: false,
      rating: 4.2,
      totalSales: 8900,
      commission: 890,
    },
  },
]

export const mockCommissionSettings: CommissionSettings = {
  defaultRate: 10.0,
  minimumRate: 5.0,
  maximumRate: 25.0,
  featuredPackageFee: 50.0,
  verificationFee: 100.0,
  customRates: [
    { serviceProviderId: "1", rate: 8.0, reason: "Yüksek hacim indirimi" },
    { serviceProviderId: "2", rate: 12.0, reason: "Standart oran" },
  ],
}

export const mockTransactions: Transaction[] = [
  {
    id: "tx_001",
    type: "commission",
    amount: 120.0,
    serviceProviderId: "1",
    serviceProviderName: "Wellness Studio",
    packageTitle: "10 Seans Pilates Paketi",
    customerName: "Mehmet Demir",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "completed",
  },
  {
    id: "tx_002",
    type: "featured_fee",
    amount: 50.0,
    serviceProviderId: "1",
    serviceProviderName: "Wellness Studio",
    packageTitle: "5 Seans Yoga Paketi",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "completed",
  },
  {
    id: "tx_003",
    type: "commission",
    amount: 89.0,
    serviceProviderId: "2",
    serviceProviderName: "Fitness Center",
    packageTitle: "8 Seans Kişisel Antrenman",
    customerName: "Zeynep Kaya",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
  },
]

export const mockMessages: Message[] = [
  {
    id: "1",
    conversationId: "conv_1",
    senderId: "3",
    receiverId: "1",
    senderType: "customer",
    receiverType: "service_provider",
    content: "Merhaba, pilates seansları hakkında bilgi alabilir miyim?",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: "2",
    conversationId: "conv_1",
    senderId: "1",
    receiverId: "3",
    senderType: "service_provider",
    receiverType: "customer",
    content: "Tabii ki! Pilates seanslarımız 60 dakika sürmekte ve kişiselleştirilmiş program hazırlıyoruz.",
    timestamp: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: "3",
    conversationId: "conv_1",
    senderId: "3",
    receiverId: "1",
    senderType: "customer",
    receiverType: "service_provider",
    content: "Harika! Randevu için müsait günlerinizi öğrenebilir miyim?",
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    isRead: false,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv_1",
    customerId: "3",
    serviceProviderId: "1",
    customerName: "Mehmet Demir",
    serviceProviderName: "Wellness Studio",
    lastMessage: "Harika! Randevu için müsait günlerinizi öğrenebilir miyim?",
    lastMessageTime: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    isActive: true,
  },
]

export const mockProviderAppointments: Appointment[] = [
  {
    id: "1",
    packagePurchaseId: "1",
    customerId: "3",
    serviceProviderId: "1",
    appointmentDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "10:00",
    endTime: "11:00",
    status: "confirmed",
    notes: "İlk seans - temel değerlendirme",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    packagePurchaseId: "1",
    customerId: "3",
    serviceProviderId: "1",
    appointmentDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "14:00",
    endTime: "15:00",
    status: "pending",
    notes: "İkinci seans",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    packagePurchaseId: "1",
    customerId: "3",
    serviceProviderId: "1",
    appointmentDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "09:00",
    endTime: "10:00",
    status: "completed",
    notes: "Başlangıç seansı tamamlandı",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockAvailableSlots: AvailableSlot[] = [
  {
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
  },
  {
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    slots: ["09:00", "10:00", "14:00", "15:00"],
  },
  {
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    slots: ["10:00", "11:00", "16:00", "17:00"],
  },
  {
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    slots: ["09:00", "14:00", "15:00", "16:00"],
  },
  {
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    slots: ["10:00", "11:00", "14:00", "15:00", "16:00"],
  },
]

export const mockTrendingPackages = mockCustomerPackages
  .filter((pkg) => pkg.isActive)
  .sort((a, b) => (b.salesCount || 0) - (a.salesCount || 0))
  .slice(0, 6)

export const mockCities = ["Tümü", "İstanbul", "Ankara", "İzmir", "Online"]

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@paresapp.online",
    password: hashPassword("admin123"), // Hash password
    firstName: "Admin",
    lastName: "User",
    userType: "admin" as const,
    isActive: true,
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    email: "provider@example.com",
    password: hashPassword("provider123"), // Hash password
    firstName: "Ayşe",
    lastName: "Yılmaz",
    userType: "service_provider" as const,
    isActive: true,
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    email: "customer@example.com",
    password: hashPassword("customer123"), // Hash password
    firstName: "Mehmet",
    lastName: "Demir",
    userType: "customer" as const,
    isActive: true,
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
